syntax = "proto3";

package lsmkv.v1;

option go_package = "lsmkv/proto";

service KVService {
  rpc Put(PutRequest) returns (PutResponse);
  rpc Get(GetRequest) returns (GetResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
}

message PutRequest {
  bytes key = 1;
  bytes value = 2;
  bool forwarded = 3;
}

message PutResponse {}

message GetRequest {
  bytes key = 1;
  bool forwarded = 2;
}

message GetResponse {
  bytes value = 1;
}

message DeleteRequest {
  bytes key = 1;
  bool forwarded = 2;
}

message DeleteResponse {}